### ISSUE TITLE
produceRecord implementation

### ISSUE THREAD

**Issue by chenharryhua** [ovotech/fs2-kafka#102]
produceRecord require ConcurrentEffect. I am wondering if Concurrent is enough for the job?

```
def doSend(data: ProducerRecord[Array[Byte], Array[Byte]]): F[F[RecordMetadata]] = {
      val run = Concurrent[F].async[RecordMetadata] { cb =>
        producer.send(
          data,
          new Callback {
            override def onCompletion(metadata: RecordMetadata, exception: Exception): Unit =
              Option(exception).fold(cb(Right(metadata)))(ex => cb(Left(ex)))
          }
        )
      }
      Concurrent[F].start(run).map(_.join)
    }
```

**Comment by chenharryhua** [comment]
my bad. it seems does not work.. If someone point me what is wrong, that would be great.

**Comment by vlovgr** [comment]
@chenharryhua `Async[F]` is enough if you want a `F[RecordMetadata]` which both calls `producer.send` and waits for the record to be sent. For performance reasons, we decouple calling `producer.send` (putting the record in the send buffer) from waiting for the record to be sent. To support the decoupling, we use a `Deferred` requiring `Concurrent[F]`. To complete the `Deferred` in the Java callback (returning `Unit`), we need `Effect[F]`. Since we require both `Concurrent[F]` and `Effect[F]`, we end up requiring `ConcurrentEffect[F]`.

**Comment by chenharryhua** [comment]
Thanks. Actually l found a major defect in my implementation - the order of messages is not maintained. Not all of them, but a few. It works well in your one.

**Comment by chenharryhua** [comment]
By the way, performance of yours is about 10 percent better, in a few rounds of testing.
