### ISSUE TITLE
Possibility to use circeJsonDeserializer

### ISSUE THREAD

**Issue by sebastianvoss** [ovotech/fs2-kafka#41]
I'm trying to use a `circeJsonDeserializer`  from [`kafka-serialization-circe`](https://github.com/ovotech/kafka-serialization) instead of a `StringDeserializer`. It works fine but when there is a message which cannot be deserialised the stream halts. I can also not recover by using `Stream.handleErrorWith`.

As a work around I'm using a `StringDeserializer` and do the JSON decoding in a `Stream.evalMap` where I catch potential exceptions thrown by `circeJsonDeserializer.deserialize`.

Is there a way to use `circeJsonDeserializer` instead of `StringDeserializer` and be able to recover from deserialisation exceptions?

**Comment by vlovgr** [comment]
Hi @sebastianvoss! This is indeed intended behaviour from kafka-serialization. If you look at the [definition](https://github.com/ovotech/kafka-serialization/blob/master/circe/src/main/scala/com/ovoenergy/kafka/serialization/circe/CirceSerialization.scala#L39) of `circeJsonDeserializer`, you'll see that it `throw`s if there's a deserialization error. This effectively means the stream is halted because processing can no longer continue (the `Fiber` running the `KafkaConsumer` finished with an exception). Even if the error would be handled in the stream, we cannot recover the `Fiber` and continue processing. (In 0.16.x the error isn't properly propagated to the stream, but that's been fixed, and will be in the next release.)

There are generally two ways to deal with this:

1. Use a deserializer which doesn't `throw`, but decodes to e.g. `Either[Error, A]`, and then handle the `Error` case in the stream. I generally recommend this approach. You can easily create one yourself, reusing most of the existing `circeJsonDeserializer` definition. I'm not directly involved with `kafka-serialization`, but I'm sure a pull request with this functionality would be appreciated.

2. Decode to a 'lower-level' format, like `Array[Byte]`, or in your case `String` (which doesn't `throw`), and then do further deserialization in the stream. This leads to a bit less clean stream definitions, so I generally recommend to avoid this approach.

If you squint a bit, you can see that `Deserializers` are just `Array[Byte] => A` for an arbitrary `A`, so it's possible to deserialize to whichever type you want, including dealing with error cases using e.g. `Either`. This library doesn't place any restrictions on (de)serializers, so you're free to implement them however you want.

**Comment by sebastianvoss** [comment]
@vlovgr: This makes perfect sense. Thanks for your comprehensive answer! I will go for option 1 and hopefully can contribute this to `kafka-serialization` soon.

**Comment by omerlh** [comment]
Hey @sebastianvoss did you ended up contributing it back? I am facing the same issue now :)
